### PR TITLE
Some upgrade and cleanup

### PR DESCRIPTION
**Pull request by calispac**
Do not merge yet. work in progress

### CODE REVIEW

**Comment by calispac** [comment]
@dneise could you review?

Basically some cleanup. No tests sorry will work on that at some point

**Comment by dneise** [comment]
Sure ... in maybe one or two hours ... no time sooner sorry.

**Comment by dneise** [comment]
Sorry had not time and overlooked it ... good that you went ahead :-(

**Comment by calispac** [comment]
no probs. anyway i think it is hard to review if I don't make unit tests... It will come at some point

**Comment by dneise** [comment]
Well .. I sometimes do not know what some stuff is about .. so I can only guess. If there are tests, I can take them as a starting point...

but here I really simply overlooked it :-(

**Pull request merged**
